import {toJSDocComment} from './toJSDocComment';

/**
 * A util method to print a warning at the start of the output file.
 */
export const addWarning = () => {
  return toJSDocComment(`This file was auto-generated by openapi-to-ts. Do not change it manually!`);
};
